// Code generated by a template
using System;
using Android.Widget;
using Android.Views;
using WAFF_Mobile.Extensions;
using Android.App;
namespace WAFF_Mobile.Extensions {
	public static class AndroidDesignerExtensions {
		public static T FindViewById<T>(this Fragment fragment, int id) 
			where T : View
		{
			return fragment.View.FindViewById<T>(id);
		}
	}
}	
