// Code generated by a template
using System;
using Android.Widget;
using Android.Views;
using WAFF_Mobile.Extensions;
namespace WAFF_Mobile {
	partial class HomeRowLayout
    {
		private LinearLayout _text;
		public LinearLayout Text { get { return _text ?? (_text =  this.FindViewById<LinearLayout>(Resource.Id.Text)); } }
		private TextView _text1;
		public TextView Text1 { get { return _text1 ?? (_text1 =  this.FindViewById<TextView>(Resource.Id.Text1)); } }
		private TextView _text2;
		public TextView Text2 { get { return _text2 ?? (_text2 =  this.FindViewById<TextView>(Resource.Id.Text2)); } }
		private ImageButton _favorite_button;
		public ImageButton favorite_button { get { return _favorite_button ?? (_favorite_button =  this.FindViewById<ImageButton>(Resource.Id.favorite_button)); } }
	}
}
