// Code generated by a template
using System;
using Android.Widget;
using Android.Views;
using WAFF_Mobile.Extensions;
namespace WAFF_Mobile {
	partial class Leaderboard {
		private ListView _listView1;
		public ListView listView1 { get { return _listView1 ?? (_listView1 =  this.FindViewById<ListView>(Resource.Id.listView1)); } }
		private RelativeLayout _backButtonContainer;
		public RelativeLayout BackButtonContainer { get { return _backButtonContainer ?? (_backButtonContainer =  this.FindViewById<RelativeLayout>(Resource.Id.BackButtonContainer)); } }
		private Button _leaderboard_backButton;
		public Button leaderboard_backButton { get { return _leaderboard_backButton ?? (_leaderboard_backButton =  this.FindViewById<Button>(Resource.Id.leaderboard_backButton)); } }
	}
}
