// Code generated by a template
using System;
using Android.Widget;
using Android.Views;
using WAFF_Mobile.Extensions;
namespace WAFF_Mobile {
	partial class Main {
		private RelativeLayout _relativeLayout1;
		public RelativeLayout relativeLayout1 { get { return _relativeLayout1 ?? (_relativeLayout1 =  this.FindViewById<RelativeLayout>(Resource.Id.relativeLayout1)); } }
		//private Fragment _menu;
		//public Fragment menu { get { return _menu ?? (_menu =  this.FindViewById<fragment>(Resource.Id.menu)); } }
		//private Fragment _content;
		//public Fragment content { get { return _content ?? (_content =  this.FindViewById<fragment>(Resource.Id.content)); } }
		private ListView _listView1;
		public ListView listView1 { get { return _listView1 ?? (_listView1 =  this.FindViewById<ListView>(Resource.Id.listView1)); } }
		private RelativeLayout _relativeLayout2;
		public RelativeLayout relativeLayout2 { get { return _relativeLayout2 ?? (_relativeLayout2 =  this.FindViewById<RelativeLayout>(Resource.Id.relativeLayout2)); } }
		private Button _leaderboard_mainButton;
		public Button leaderboard_mainButton { get { return _leaderboard_mainButton ?? (_leaderboard_mainButton =  this.FindViewById<Button>(Resource.Id.leaderboard_mainButton)); } }
		private Button _favorites;
		public Button favorites { get { return _favorites ?? (_favorites =  this.FindViewById<Button>(Resource.Id.favorites)); } }
	}
}
