// Code generated by a template
using System;
using Android.Widget;
using Android.Views;
using WAFF_Mobile.Extensions;
namespace WAFF_Mobile {
	partial class ThankYou {
		private LinearLayout _linearLayout1;
		public LinearLayout linearLayout1 { get { return _linearLayout1 ?? (_linearLayout1 =  this.FindViewById<LinearLayout>(Resource.Id.linearLayout1)); } }
		private TextView _textView1;
		public TextView textView1 { get { return _textView1 ?? (_textView1 =  this.FindViewById<TextView>(Resource.Id.textView1)); } }
		private TextView _textView2;
		public TextView textView2 { get { return _textView2 ?? (_textView2 =  this.FindViewById<TextView>(Resource.Id.textView2)); } }
		private Button _button1;
		public Button button1 { get { return _button1 ?? (_button1 =  this.FindViewById<Button>(Resource.Id.button1)); } }
	}
}
