#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("WAFF_Mobile.Resource", IsApplication=true)]

namespace WAFF_Mobile
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public const int primaryColor = 2130968576;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ab_bottom_solid_styled = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ab_solid_styled = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ab_stacked_solid_styled = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int blank = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_action_location = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_action_menu = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_action_refresh = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_action_settings = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ic_launcher = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int Icon = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int list_focused_styled = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int menu_dropdown_panel_styled = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int progress_bg_styled = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int progress_primary_styled = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int progress_secondary_styled = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int spinner_ab_default_styled = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int spinner_ab_disabled_styled = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int spinner_ab_focused_styled = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int spinner_ab_pressed_styled = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int star_off = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int star_on = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int tab_selected_focused_styled = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int tab_selected_pressed_styled = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int tab_selected_styled = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int tab_unselected_focused_styled = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int tab_unselected_pressed_styled = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int tile = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int unavailable = 2130837531;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080005
			public const int BackButtonContainer = 2131230725;
			
			// aapt resource value: 0x7f080000
			public const int Text = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int Text1 = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int Text2 = 2131230722;
			
			// aapt resource value: 0x7f080008
			public const int WAFF_toolbar = 2131230728;
			
			// aapt resource value: 0x7f080011
			public const int action_favorites = 2131230737;
			
			// aapt resource value: 0x7f080010
			public const int action_refresh = 2131230736;
			
			// aapt resource value: 0x7f080012
			public const int action_settings = 2131230738;
			
			// aapt resource value: 0x7f08000f
			public const int button1 = 2131230735;
			
			// aapt resource value: 0x7f080003
			public const int favorite_button = 2131230723;
			
			// aapt resource value: 0x7f08000b
			public const int favorites = 2131230731;
			
			// aapt resource value: 0x7f080006
			public const int leaderboard_backButton = 2131230726;
			
			// aapt resource value: 0x7f08000a
			public const int leaderboard_mainButton = 2131230730;
			
			// aapt resource value: 0x7f08000c
			public const int linearLayout1 = 2131230732;
			
			// aapt resource value: 0x7f080004
			public const int listView1 = 2131230724;
			
			// aapt resource value: 0x7f080007
			public const int relativeLayout1 = 2131230727;
			
			// aapt resource value: 0x7f080009
			public const int relativeLayout2 = 2131230729;
			
			// aapt resource value: 0x7f08000d
			public const int textView1 = 2131230733;
			
			// aapt resource value: 0x7f08000e
			public const int textView2 = 2131230734;
			
			// aapt resource value: 0x7f080013
			public const int uninstall = 2131230739;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int HomeRowLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Leaderboard = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int listView = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int ThankYou = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int WaffUITheme = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f070000
			public const int Options = 2131165184;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int appName = 2131034113;
			
			// aapt resource value: 0x7f050004
			public const int favOff = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int favOn = 2131034117;
			
			// aapt resource value: 0x7f050000
			public const int hello = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int options = 2131034115;
			
			// aapt resource value: 0x7f050006
			public const int settings = 2131034118;
			
			// aapt resource value: 0x7f050002
			public const int title = 2131034114;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int Theme = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
